# Generated by Django 5.2.8 on 2025-12-11 10:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_shift', models.CharField(choices=[('Pagi', 'Pagi (06:00 - 14:00)'), ('Sore', 'Sore (14:00 - 22:00)'), ('Malam', 'Malam (22:00 - 06:00)')], max_length=20, unique=True)),
                ('jam_mulai', models.TimeField()),
                ('jam_selesai', models.TimeField()),
                ('tunjangan_shift', models.PositiveIntegerField(default=0, help_text='Tunjangan tambahan per hari (Rupiah)')),
            ],
            options={
                'verbose_name': 'Shift',
                'verbose_name_plural': 'Daftar Shift',
                'ordering': ['jam_mulai'],
            },
        ),
        migrations.CreateModel(
            name='Pegawai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_induk_pegawai', models.CharField(max_length=20, unique=True)),
                ('no_ktp', models.CharField(max_length=20, unique=True)),
                ('no_telepon', models.CharField(max_length=15)),
                ('alamat', models.TextField()),
                ('jabatan', models.CharField(choices=[('Manager', 'Manager'), ('Staff Admin', 'Staff Admin'), ('Staff Rental', 'Staff Rental'), ('Mekanik', 'Mekanik'), ('Driver', 'Driver'), ('Security', 'Security')], max_length=50)),
                ('departemen', models.CharField(choices=[('Admin', 'Admin'), ('Rental', 'Rental'), ('Teknis', 'Teknis'), ('Keamanan', 'Keamanan')], max_length=50)),
                ('tanggal_bergabung', models.DateField()),
                ('gaji_pokok', models.PositiveIntegerField(help_text='Gaji pokok per bulan (Rupiah)')),
                ('status', models.CharField(choices=[('Aktif', 'Aktif'), ('Cuti', 'Cuti'), ('Berhenti', 'Berhenti'), ('Non-Aktif', 'Non-Aktif')], default='Aktif', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pegawai_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pegawai',
                'verbose_name_plural': 'Daftar Pegawai',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoriKerjaPegawai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipe_aktivitas', models.CharField(choices=[('Masuk', 'Masuk'), ('Keluar', 'Keluar'), ('Izin', 'Izin'), ('Sakit', 'Sakit'), ('Cuti', 'Cuti'), ('Terlambat', 'Terlambat'), ('Tepat Waktu', 'Tepat Waktu')], max_length=20)),
                ('tanggal_waktu', models.DateTimeField(default=django.utils.timezone.now)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('pegawai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histori_kerja', to='manajemen_pegawai.pegawai')),
            ],
            options={
                'verbose_name': 'Histori Kerja',
                'verbose_name_plural': 'Histori Kerja Pegawai',
                'ordering': ['-tanggal_waktu'],
            },
        ),
        migrations.CreateModel(
            name='Penghargaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipe', models.CharField(choices=[('Bonus', 'Bonus'), ('Insentif', 'Insentif'), ('THR', 'Tunjangan Hari Raya'), ('Penghargaan', 'Penghargaan Kinerja'), ('Lainnya', 'Lainnya')], max_length=50)),
                ('nominal', models.PositiveIntegerField()),
                ('tanggal', models.DateField(default=django.utils.timezone.now)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pegawai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penghargaan', to='manajemen_pegawai.pegawai')),
            ],
            options={
                'verbose_name': 'Penghargaan',
                'verbose_name_plural': 'Penghargaan Pegawai',
                'ordering': ['-tanggal'],
            },
        ),
        migrations.CreateModel(
            name='JadwalKerja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_mulai', models.DateField()),
                ('tanggal_selesai', models.DateField(blank=True, null=True)),
                ('pegawai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jadwal_kerja', to='manajemen_pegawai.pegawai')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manajemen_pegawai.shift')),
            ],
            options={
                'verbose_name': 'Jadwal Kerja',
                'verbose_name_plural': 'Jadwal Kerja Pegawai',
                'ordering': ['-tanggal_mulai'],
            },
        ),
        migrations.CreateModel(
            name='GajiPegawai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bulan', models.DateField(help_text='Tanggal awal bulan gaji (contoh: 2024-12-01)')),
                ('gaji_pokok', models.PositiveIntegerField()),
                ('tunjangan', models.PositiveIntegerField(default=0, help_text='Total tunjangan')),
                ('potongan', models.PositiveIntegerField(default=0, help_text='Total potongan')),
                ('total_gaji', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('Belum Dibayar', 'Belum Dibayar'), ('Menunggu Verifikasi', 'Menunggu Verifikasi'), ('Sudah Dibayar', 'Sudah Dibayar')], default='Belum Dibayar', max_length=20)),
                ('tanggal_pembayaran', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dibayar_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gaji_yang_dibayarkan', to=settings.AUTH_USER_MODEL)),
                ('pegawai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gaji_pegawai', to='manajemen_pegawai.pegawai')),
            ],
            options={
                'verbose_name': 'Gaji Pegawai',
                'verbose_name_plural': 'Slip Gaji Pegawai',
                'ordering': ['-bulan'],
                'unique_together': {('pegawai', 'bulan')},
            },
        ),
    ]
