# Generated by Django 5.2.8 on 2025-12-17 11:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_pegawai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pegawai',
            name='jumlah_trip',
            field=models.PositiveIntegerField(default=0, help_text='Total perjalanan yang sudah ditugaskan.'),
        ),
        migrations.AddField(
            model_name='pegawai',
            name='rating',
            field=models.FloatField(default=5.0, help_text='Rating kinerja (1.0 - 5.0). Diinput manual oleh Admin.', validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
    ]
