# Generated by Django 5.2.8 on 2025-12-11 10:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kendaraan_ext', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilPengguna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_ktp', models.CharField(blank=True, max_length=20, null=True)),
                ('no_sim', models.CharField(blank=True, max_length=20, null=True)),
                ('no_telepon', models.CharField(blank=True, max_length=15, null=True)),
                ('alamat', models.TextField(blank=True, null=True)),
                ('is_pegawai', models.BooleanField(default=False)),
                ('jabatan', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reservasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tgl_mulai', models.DateField()),
                ('tgl_selesai', models.DateField()),
                ('tgl_pengembalian_aktual', models.DateField(blank=True, null=True)),
                ('total_biaya', models.DecimalField(decimal_places=0, max_digits=12)),
                ('status', models.CharField(choices=[('Dipesan', 'Dipesan'), ('Aktif', 'Aktif'), ('Selesai', 'Selesai'), ('Batal', 'Batal')], default='Dipesan', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kendaraan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kendaraan_ext.kendaraan')),
                ('pelanggan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservasi_saya', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tagihan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_denda', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('total_akhir', models.DecimalField(decimal_places=0, max_digits=12)),
                ('status', models.CharField(choices=[('Belum Lunas', 'Belum Lunas'), ('Menunggu Verifikasi', 'Menunggu Verifikasi'), ('Lunas', 'Lunas')], default='Belum Lunas', max_length=20)),
                ('reservasi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='manajemen_pengguna.reservasi')),
            ],
        ),
        migrations.CreateModel(
            name='Pembayaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.DecimalField(decimal_places=0, max_digits=12)),
                ('tanggal', models.DateTimeField(default=django.utils.timezone.now)),
                ('metode', models.CharField(choices=[('Tunai', 'Tunai'), ('Transfer', 'Transfer')], max_length=10)),
                ('bukti_transfer', models.ImageField(blank=True, null=True, upload_to='bukti_bayar/')),
                ('diterima_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tagihan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riwayat_pembayaran', to='manajemen_pengguna.tagihan')),
            ],
        ),
        migrations.CreateModel(
            name='Denda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(max_length=50)),
                ('jumlah', models.DecimalField(decimal_places=0, max_digits=12)),
                ('keterangan', models.TextField(blank=True)),
                ('tagihan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daftar_denda', to='manajemen_pengguna.tagihan')),
            ],
        ),
    ]
