# Generated by Django 5.2.8 on 2025-12-11 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_pengguna', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pembayaran',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
    ]
