# Generated by Django 5.2.8 on 2025-12-17 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_pegawai', '0001_initial'),
        ('manajemen_pengguna', '0002_pembayaran_is_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservasi',
            name='biaya_supir',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='reservasi',
            name='pakai_supir',
            field=models.BooleanField(default=False, verbose_name='Pakai Sopir?'),
        ),
        migrations.AddField(
            model_name='reservasi',
            name='supir',
            field=models.ForeignKey(blank=True, limit_choices_to={'jabatan': 'Driver'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='riwayat_menyetir', to='manajemen_pegawai.pegawai'),
        ),
    ]
