# Generated by Django 5.2.8 on 2025-12-04 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kendaraan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plat_nomor', models.CharField(max_length=20, unique=True)),
                ('merk', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('tahun', models.PositiveIntegerField()),
                ('harga_sewa_per_hari', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('Tersedia', 'Tersedia'), ('Dirental', 'Dirental'), ('Perawatan', 'Perawatan')], default='Tersedia', max_length=20)),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='kendaraan/')),
                ('tipe_kepemilikan', models.CharField(choices=[('Milik Sendiri', 'Milik Sendiri'), ('Mitra', 'Mitra')], default='Milik Sendiri', max_length=20)),
                ('id_mitra', models.CharField(blank=True, max_length=50, null=True)),
                ('persen_bagi_hasil', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': 'Kendaraan',
                'verbose_name_plural': 'Daftar Kendaraan',
            },
        ),
        migrations.CreateModel(
            name='Garasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lokasi', models.CharField(max_length=100)),
                ('kendaraan', models.ManyToManyField(to='kendaraan_ext.kendaraan')),
            ],
        ),
        migrations.CreateModel(
            name='KendaraanExt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kendaraan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kendaraan_ext.kendaraan')),
            ],
        ),
        migrations.CreateModel(
            name='Mobil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah_kursi', models.PositiveIntegerField()),
                ('transmisi', models.CharField(max_length=20)),
                ('kendaraan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail_mobil', to='kendaraan_ext.kendaraan')),
            ],
        ),
        migrations.CreateModel(
            name='Motor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipe_motor', models.CharField(max_length=30)),
                ('kapasitas_mesin_cc', models.PositiveIntegerField()),
                ('kendaraan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail_motor', to='kendaraan_ext.kendaraan')),
            ],
        ),
    ]
